FROM randomdude/gcc-cross-x86_64-elf

RUN apt-get update 
RUN apt-get upgrade -y

RUN apt-get install -y nasm             ;it helps to write assembly code
RUN apt-get install -y xorriso
RUN apt-get install -y grub-pc-bin      ;group package to finally build the file
RUN apt-get install -y grub-common



VOLUME /root/env                        ;to have access to all the files we created
WORKDIR /root/env
